### ISSUE TITLE
basePath and assetPrefix config breaks local runs

### ISSUE THREAD

**Issue by jochemloedeman** [godatadriven/github-contributions#24]
we set 
``` 
basePath: '/github-contributions',
assetPrefix: '/github-contributions/'
```
to place resources correctly for deployment with github pages. However, it breaks local runs with `npm run dev`. We can make the values of these fields dependent on the run scenario.

**Comment by ramonvermeulen** [comment]
Closing this issue, should be solved with current set-up.
