### ISSUE TITLE
Generate HTML page with visualisation and publish on Github pages

### ISSUE THREAD

**Issue by JCZuurmond** [godatadriven/github-contributions#6]
# Process

1. Build a script that reads the data and writes a HTML page with visualisation
2. Automate the script in the CI
3. Publish on Github pages

# Visulations

V1 would look like:
1. Top five projects based on:
    - `# unique contributors`
    - `# PR`
    - most recent PR ("hot" projects)
2. Top five PR:
    - Most recent
    - Most emoji's (within last six or twelve months)
3. Top organizations

 Maybe a list of the top five, maybe a visualization of the total, maybe highlight some stuff, have fun creating something nice!

**Comment by timotk** [comment]
@yildizali I can recommend using something like jinja to create your static html. Contact me if you need help with it :)

**Comment by timotk** [comment]
See https://github.com/godatadriven/github-contributions/pull/9 for an example :)

**Comment by JCZuurmond** [comment]
@jrderuiter recommend [materialize](https://materializecss.com/) to quickly build fancy looking pages

**Comment by timotk** [comment]
I think this can be closed because of:
- #18 
- #17 
- #12 
- #9 

@jochemloedeman can you track the dashboard creation in a separate issue ?
