### ISSUE TITLE
It would be great if we could add these people

### ISSUE THREAD

**Issue by jessehouwing** [godatadriven/github-contributions#64]
- [ ] @0xR
 - [ ] @AlbertBrand
 - [ ] @alycklama
 - [ ] @bschaatsbergen
 - [ ] @chtzvt
 - [ ] @cloudcosmonaut
 - [ ] @cvs79
 - [ ] @DanielRieske
 - [ ] @dgniewek
 - [ ] @droosma
 - [ ] @fvanwijk
 - [ ] @hernanif1
 - [ ] @hierynomus
 - [ ] @Jacco
 - [ ] @jwbargsten
 - [ ] @krisgeus
 - [ ] @laurensknoll
 - [ ] @NoirNoble
 - [ ] @Nr18
 - [ ] @OmnipotentOwl
 - [ ] @ramonvermeulen
 - [ ] @sanderaernouts
 - [ ] @sujithq
 - [ ] @ThijSlim
 - [ ] @thomas-vl
 - [ ] @tiborhercz
 - [ ] @Yeseh
 - [ ] @mwiewior

**Comment by mwiewior** [comment]
hey @jessehouwing - what's the reason for removing me from the list ?

**Comment by jessehouwing** [comment]
I wasn't 100% sure based on your GitHub profile whether we should include you. Added you back in.

**Comment by PatMyron** [comment]
> hey @jessehouwing - what's the reason for removing me from the list ?

Also not sure why I was added then removed

Looks like a great tool and would be awesome if anyone could use it
