### ISSUE TITLE
Repository tile is not clickable

### ISSUE THREAD

**Issue by nfx** [godatadriven/github-contributions#87]
Given:

1. go to https://godatadriven.github.io/github-contributions/
2. pick @JCZuurmond as author
3. scroll down to tiles
4. click on `soda-spark`
5. ??. why am I not taken to commits of @JCZuurmond to soda-spark - https://github.com/godatadriven/soda-spark/commits/main/?author=JCZuurmond

<img width="812" alt="image" src="https://github.com/godatadriven/github-contributions/assets/259697/874ea91c-8376-474f-bc47-1d5d8134f552">

**Comment by JCZuurmond** [comment]
@nfx : Thanks for your suggestion. That would be a nice feature indeed!

**Comment by ramonvermeulen** [comment]
@nfx Made a PR for this: https://github.com/godatadriven/github-contributions/pull/88
Functionality only works when there is an author selected.

**Comment by ramonvermeulen** [comment]
Thinking about it, maybe I can add the same functionality on bar charts when an author is selected.
E.g.: https://github.com/pulls?q=author%3AJCZuurmond+created%3A2023-11-01..2023-12-01

**Comment by nfx** [comment]
I had to click through repositories manually today without this feature:)

**Comment by ramonvermeulen** [comment]
Closed by https://github.com/godatadriven/github-contributions/pull/88
